import React, { useState } from 'react';
import { api, attempt } from '../utils/api';
import {
  Dialog, DialogTitle, DialogContent, DialogActions, Button, TextField, FormControl, InputLabel, Select, MenuItem, Box, Typography, Chip, CircularProgress, Stack
, Alert
} from '@mui/material';
import AutoAwesomeIcon from '@mui/icons-material/AutoAwesome';

const AVAILABLE_MCP_TOOLS = [
  'mcp-google-search',
  'mcp-pgvector-search',
  'mcp-redis-queue',
  'mcp-sql-query',
  'mcp-http-fetcher',
  'mcp-code-executor',
  'mcp-file-storage'
];

export default function MaterializeAgentModal({ open, onClose, state, onSubmit }) {
  const [name, setName] = useState('');
  const [parent, setParent] = useState(`creator-${state.projectId}`);
  const [userGoal, setUserGoal] = useState('');
  const [systemPrompt, setSystemPrompt] = useState('');
  const [selectedTools, setSelectedTools] = useState(['mcp-pgvector-search', 'mcp-redis-queue']);
  const [generating, setGenerating] = useState(false);

  const [generateError, setGenerateError] = useState(null);

  const handleGenerateSystemPrompt = async () => {
    if (!userGoal.trim()) return;
    setGenerating(true);
    setGenerateError(null);
    const { data, error } = await attempt(api.post('/api/generate-system-prompt', {
      user_prompt: userGoal,
      target_role: name || 'Specialized Worker Agent',
    }));
    if (error) {
      // The fallback used to quietly substitute a one-line prompt of its own,
      // so a user could materialise an agent believing the model had written
      // its instructions. The failure is shown; the field is left alone.
      setGenerateError(error);
    } else {
      setSystemPrompt(data.system_prompt || '');
    }
    setGenerating(false);
  };

  const handleSubmit = () => {
    onSubmit({
      name: name || 'CustomWorker',
      parentId: parent,
      systemPrompt: systemPrompt || `Specialized worker agent assigned to goal: ${userGoal}`,
      tools: selectedTools
    });
    setName('');
    setUserGoal('');
    setSystemPrompt('');
    onClose();
  };

  return (
    <Dialog open={open} onClose={onClose} maxWidth="sm" fullWidth>
      <DialogTitle sx={{ fontWeight: 700 }}>
        🤖 Materialize Progeny Worker Agent via Kagent
      </DialogTitle>
      <DialogContent sx={{ display: 'flex', flexDirection: 'column', gap: 2, pt: 1 }}>
        <TextField
          label="Agent Name"
          size="small"
          fullWidth
          placeholder="e.g. DataSynthesizerWorker"
          value={name}
          onChange={(e) => setName(e.target.value)}
        />

        <FormControl size="small" fullWidth>
          <InputLabel>Parent Agent (Progeny Origin)</InputLabel>
          <Select
            value={parent}
            label="Parent Agent (Progeny Origin)"
            onChange={(e) => setParent(e.target.value)}
          >
            <MenuItem value={`creator-${state.projectId}`}>AgentCreator-{state.projectId}</MenuItem>
            <MenuItem value={`conductor-${state.projectId}`}>ConductorAgent-{state.projectId}</MenuItem>
            <MenuItem value={`react-${state.projectId}`}>ReActAgent-{state.projectId}</MenuItem>
          </Select>
        </FormControl>

        {/* User Goal Prompt -> LLM System Prompt Generator */}
        <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1, p: 2, borderRadius: 2, backgroundColor: 'rgba(9, 13, 22, 0.7)', border: '1px solid rgba(255,255,255,0.08)' }}>
          <Typography variant="subtitle2" sx={{ fontWeight: 700, color: '#60a5fa', display: 'flex', alignItems: 'center', gap: 0.8 }}>
            <AutoAwesomeIcon sx={{ fontSize: 18 }} /> High-Level Goal Prompt
          </Typography>

          <TextField
            placeholder="Describe what this agent should do (e.g. Process raw financial records, extract metrics, and output JSON)..."
            size="small"
            fullWidth
            multiline
            rows={2}
            value={userGoal}
            onChange={(e) => setUserGoal(e.target.value)}
          />

          <Button
            variant="contained"
            color="secondary"
            size="small"
            startIcon={generating ? <CircularProgress size={16} color="inherit" /> : <AutoAwesomeIcon />}
            onClick={handleGenerateSystemPrompt}
            disabled={generating || !userGoal.trim()}
          >
            {generating ? 'Generating System Prompt...' : '🪄 Generate System Prompt via LLM'}
          </Button>
        </Box>

        {/* System Prompt Output */}
        <TextField
          label="Generated System Prompt"
          size="small"
          fullWidth
          multiline
          rows={4}
          value={systemPrompt}
          onChange={(e) => setSystemPrompt(e.target.value)}
          placeholder="System prompt generated by LLM will appear here..."
        />

        {/* Selectable MCP Tools */}
        <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
          <Typography variant="caption" sx={{ fontWeight: 700, color: 'text.secondary' }}>
            Select MCP Tools to Attach
          </Typography>
          <Stack direction="row" spacing={1} flexWrap="wrap" useFlexGap>
            {AVAILABLE_MCP_TOOLS.map((t) => {
              const selected = selectedTools.includes(t);
              return (
                <Chip
                  key={t}
                  label={t}
                  color={selected ? "primary" : "default"}
                  variant={selected ? "filled" : "outlined"}
                  onClick={() => {
                    if (selected) {
                      setSelectedTools(selectedTools.filter(x => x !== t));
                    } else {
                      setSelectedTools([...selectedTools, t]);
                    }
                  }}
                  sx={{ cursor: 'pointer', fontSize: '0.75rem', fontWeight: 600 }}
                />
              );
            })}
          </Stack>
        </Box>
      </DialogContent>

      {generateError && (
          <Alert severity="error" sx={{ mx: 3, mb: 1 }} onClose={() => setGenerateError(null)}>
            {generateError.userMessage}
          </Alert>
        )}
        <DialogActions sx={{ px: 3, pb: 2 }}>
        <Button onClick={onClose} color="inherit">Cancel</Button>
        <Button onClick={handleSubmit} variant="contained" color="primary">
          Materialize Agent via Kagent
        </Button>
      </DialogActions>
    </Dialog>
  );
}
