// Parity with genome_core/forms.py: golden values generated by Python.
// interface-spec Rule 6.13 made executable.
import { describe, it, expect } from "vitest";
import { legTimes, routePosition, routeHeading, pileQuantity,
         isoProject, isoUnproject } from "./forms.js";
import golden from "./golden.json";

const close = (a, b, eps = 1e-6) => Math.abs(a - b) < eps;

describe("closed-form parity with the server", () => {
  const w = golden.waypoints;
  it("arrival time matches Python", () => {
    const times = legTimes(w, golden.departed_at);
    expect(close(times[times.length - 1], golden.arrives_at)).toBe(true);
  });
  it("positions match at 25% and 60%", () => {
    const span = golden.arrives_at - golden.departed_at;
    for (const [frac, key] of [[0.25, "pos_25pct"], [0.6, "pos_60pct"]]) {
      const p = routePosition(w, golden.departed_at,
                              golden.departed_at + span * frac);
      expect(close(p[0], golden[key][0])).toBe(true);
      expect(close(p[1], golden[key][1])).toBe(true);
    }
  });
  it("heading matches on the final leg", () => {
    expect(close(routeHeading(w, golden.departed_at, golden.arrives_at - 1),
                 golden.heading_late)).toBe(true);
  });
  it("pile quantity matches, including the cap clamp", () => {
    expect(close(pileQuantity(golden.pile, 1000), golden.pile_q_1000)).toBe(true);
    expect(close(pileQuantity(golden.pile, 10000), golden.pile_q_cap)).toBe(true);
  });
  it("iso round-trips (hit-testing is the inverse, Rule 6.5)", () => {
    const p = [0.31, 0.77];
    const back = isoUnproject(isoProject(p));
    expect(close(back[0], p[0])).toBe(true);
    expect(close(back[1], p[1])).toBe(true);
  });
});
